name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
          usedocker: true
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
          HD_HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
